@startuml QuackstagramERD
entity "User" as user {
  + username : varchar(255)
  --
  bio : varchar(255)
  password : varchar(255)
  postsCount : int
  followersCount : int
  followingCount : int
}

entity "Post" as post {
  + id : int
  --
  imagePath : varchar(255)
  caption : varchar(255)
  likesCount : int
  username : User
}

entity "PostLike" as postlike {
  + id : int
  --
  username : User
  postId : Post
}

entity "Follow" as follow {
  + id : int
  --
  username : User
  target : User
}

entity "Notification" as notification {
  + id : int
  --
  username : User
  target : User
}

user "1" -- "0..*" post
user "1" -- "0..*" postlike
user "1" -- "0..*" follow
user "1" -- "0..*" notification
notification "1" -- "1" post
post "1" -- "0..*" postlike
@enduml